from datetime import date
from copy import deepcopy
from threading import Lock

import pandas as pd

from app.config import settings
from app.services import ai_analysis_service
from app.services.holiday_service import holiday_context
from app.services.weather_service import weather_context
from app.utils.date_utils import period_buckets, resolve_period


VALID_SCOPE_TYPES = {"total", "city", "building", "apartment"}
_CHART_CACHE: dict[tuple, dict] = {}
_CACHE_LOCK = Lock()
_CACHE_REVISION = 0


def invalidate_analysis_cache() -> None:
    global _CACHE_REVISION
    with _CACHE_LOCK:
        _CACHE_REVISION += 1
        _CHART_CACHE.clear()


def _chart_cache_key(
    scope_type: str,
    scope_id: str | None,
    period: str,
    offset: int,
    include_weather: bool,
    analysis_provider: str | None,
) -> tuple:
    return (
        _CACHE_REVISION,
        scope_type,
        scope_id or "",
        period,
        offset,
        include_weather,
        (analysis_provider or "").lower(),
    )


def _scope_where(scope_type: str, scope_id: str | None) -> tuple[str, list]:
    # Scope filtering is centralized so navigation, chart, report and chat use
    # the same meaning of total/city/building/apartment.
    if scope_type not in VALID_SCOPE_TYPES:
        raise ValueError(f"Invalid scope_type: {scope_type}")
    if scope_type == "total":
        return "", []
    if not scope_id:
        raise ValueError(f"scope_id is required for scope_type={scope_type}")

    column = {
        "city": "city_id",
        "building": "building_id",
        "apartment": "apartment_id",
    }[scope_type]
    return f"WHERE {column} = ?", [scope_id]


def _read_frame(connection, scope_type: str = "total", scope_id: str | None = None) -> pd.DataFrame:
    where, params = _scope_where(scope_type, scope_id)
    query = f"SELECT * FROM consumption_records {where}"
    return pd.read_sql_query(query, connection, params=params)


def _summary(frame: pd.DataFrame) -> dict:
    # These are hard deterministic KPIs. They are never generated by AI.
    if frame.empty:
        return {
            "total_energy_kwh": 0.0,
            "total_co2_kg": 0.0,
            "estimated_cost_eur": 0.0,
            "record_count": 0,
            "city_count": 0,
            "building_count": 0,
            "apartment_count": 0,
            "date_from": None,
            "date_to": None,
        }

    total_energy = float(frame["energyusage_kwh"].sum())
    total_co2_kg = float(frame["co2_g"].sum() / 1000)
    return {
        "total_energy_kwh": round(total_energy, 3),
        "total_co2_kg": round(total_co2_kg, 3),
        "estimated_cost_eur": round(total_energy * settings.energy_price_eur_per_kwh, 2),
        "record_count": int(len(frame)),
        "city_count": int(frame["city_id"].nunique()),
        "building_count": int(frame["building_id"].nunique()),
        "apartment_count": int(frame["apartment_id"].nunique()),
        "date_from": str(frame["date"].min()),
        "date_to": str(frame["date"].max()),
    }


def _scope_info(frame: pd.DataFrame, scope_type: str, scope_id: str | None) -> dict:
    if scope_type == "total":
        return {"type": "total", "id": "total", "label": "Gesamtbestand"}
    if frame.empty:
        return {"type": scope_type, "id": scope_id, "label": scope_id or scope_type}

    row = frame.iloc[0]
    if scope_type == "city":
        return {"type": "city", "id": row["city_id"], "label": row["city"], "city": row["city"]}
    if scope_type == "building":
        label = f"{row['street']} {row['housenumber']}, {row['city']}"
        return {
            "type": "building",
            "id": row["building_id"],
            "label": label,
            "city": row["city"],
            "street": row["street"],
            "housenumber": row["housenumber"],
        }
    label = f"Wohnung {row['apartment_number']}, {row['street']} {row['housenumber']}, {row['city']}"
    return {
        "type": "apartment",
        "id": row["apartment_id"],
        "label": label,
        "apartment_number": row["apartment_number"],
        "building_id": row["building_id"],
    }


def navigation_overview(connection) -> dict:
    frame = _read_frame(connection)
    cities = []
    if not frame.empty:
        grouped = frame.groupby(["city_id", "city"], as_index=False).agg(
            energyusage_kwh=("energyusage_kwh", "sum"),
            co2_g=("co2_g", "sum"),
            building_count=("building_id", "nunique"),
            apartment_count=("apartment_id", "nunique"),
        )
        for row in grouped.sort_values("city").to_dict(orient="records"):
            cities.append(
                {
                    "city_id": row["city_id"],
                    "city": row["city"],
                    "total_energy_kwh": round(float(row["energyusage_kwh"]), 3),
                    "total_co2_kg": round(float(row["co2_g"]) / 1000, 3),
                    "building_count": int(row["building_count"]),
                    "apartment_count": int(row["apartment_count"]),
                }
            )
    return {"scope": _scope_info(frame, "total", None), "summary": _summary(frame), "cities": cities}


def city_details(connection, city_id: str) -> dict:
    frame = _read_frame(connection, "city", city_id)
    buildings = []
    if not frame.empty:
        grouped = frame.groupby(["building_id", "street", "housenumber", "city"], as_index=False).agg(
            energyusage_kwh=("energyusage_kwh", "sum"),
            co2_g=("co2_g", "sum"),
            apartment_count=("apartment_id", "nunique"),
        )
        for row in grouped.sort_values(["street", "housenumber"]).to_dict(orient="records"):
            building_frame = frame[frame["building_id"] == row["building_id"]]
            mold_risk = _mold_risk_assessment(building_frame, None, None, "month")
            buildings.append(
                {
                    "building_id": row["building_id"],
                    "address": f"{row['street']} {row['housenumber']}",
                    "city": row["city"],
                    "total_energy_kwh": round(float(row["energyusage_kwh"]), 3),
                    "total_co2_kg": round(float(row["co2_g"]) / 1000, 3),
                    "apartment_count": int(row["apartment_count"]),
                    "mold_risk": {"score": mold_risk["score"], "level": mold_risk["level"], "label": mold_risk["label"]},
                }
            )
    return {"scope": _scope_info(frame, "city", city_id), "summary": _summary(frame), "buildings": buildings}


def building_details(connection, building_id: str) -> dict:
    frame = _read_frame(connection, "building", building_id)
    apartments = []
    if not frame.empty:
        grouped = frame.groupby(["apartment_id", "apartment_number"], as_index=False).agg(
            energyusage_kwh=("energyusage_kwh", "sum"),
            co2_g=("co2_g", "sum"),
            livingspace_m2=("livingspace_m2", "max"),
            roomnumber=("roomnumber", "max"),
        )
        for row in grouped.sort_values("apartment_number").to_dict(orient="records"):
            apartment_frame = frame[frame["apartment_id"] == row["apartment_id"]]
            mold_risk = _mold_risk_assessment(apartment_frame, None, None, "month")
            apartments.append(
                {
                    "apartment_id": row["apartment_id"],
                    "apartment_number": row["apartment_number"],
                    "total_energy_kwh": round(float(row["energyusage_kwh"]), 3),
                    "total_co2_kg": round(float(row["co2_g"]) / 1000, 3),
                    "livingspace_m2": round(float(row["livingspace_m2"]), 1),
                    "roomnumber": int(row["roomnumber"]),
                    "mold_risk": {"score": mold_risk["score"], "level": mold_risk["level"], "label": mold_risk["label"]},
                }
            )
    return {"scope": _scope_info(frame, "building", building_id), "summary": _summary(frame), "apartments": apartments}


def apartment_details(connection, apartment_id: str) -> dict:
    frame = _read_frame(connection, "apartment", apartment_id)
    metadata = {}
    if not frame.empty:
        row = frame.iloc[0]
        mold_risk = _mold_risk_assessment(frame, None, None, "month")
        metadata = {
            "city": row["city"],
            "zipcode": row["zipcode"],
            "street": row["street"],
            "housenumber": row["housenumber"],
            "apartment_number": row["apartment_number"],
            "building_id": row["building_id"],
            "energysource": row["energysource"],
            "livingspace_m2": float(row["livingspace_m2"]),
            "roomnumber": int(row["roomnumber"]),
            "unitnumber": row["unitnumber"],
            "mold_risk": mold_risk,
        }
    return {"scope": _scope_info(frame, "apartment", apartment_id), "summary": _summary(frame), "metadata": metadata}


def _frame_for_period(frame: pd.DataFrame, start: date, end: date) -> pd.DataFrame:
    if frame.empty:
        return frame
    data = frame.copy()
    data["date"] = pd.to_datetime(data["date"]).dt.date
    return data[(data["date"] >= start) & (data["date"] <= end)]


def _aggregate_series(frame: pd.DataFrame, labels: list[str], granularity: str) -> tuple[list[float], list[float]]:
    # Return one value for every x-axis label, including explicit zeros for
    # missing days/months so the frontend can draw stable series.
    if frame.empty:
        return [0.0 for _ in labels], [0.0 for _ in labels]
    data = frame.copy()
    data["date"] = pd.to_datetime(data["date"])
    data["bucket"] = data["date"].dt.strftime("%Y-%m" if granularity == "month" else "%Y-%m-%d")
    grouped = data.groupby("bucket").agg(energy=("energyusage_kwh", "sum"), co2=("co2_g", "sum"))
    energy = [round(float(grouped.loc[label]["energy"]), 3) if label in grouped.index else 0.0 for label in labels]
    co2 = [round(float(grouped.loc[label]["co2"]) / 1000, 3) if label in grouped.index else 0.0 for label in labels]
    return energy, co2


def _baseline_energy(full_frame: pd.DataFrame, labels: list[str], granularity: str, weather: list[dict]) -> list[float]:
    # This deterministic baseline is handed to the chart provider as context.
    # The local algorithm uses it directly; Vertex can refine it but must validate.
    if full_frame.empty:
        return [0.0 for _ in labels]

    data = full_frame.copy()
    data["date"] = pd.to_datetime(data["date"])
    data["bucket"] = data["date"].dt.strftime("%Y-%m" if granularity == "month" else "%Y-%m-%d")
    historical = data.groupby("bucket")["energyusage_kwh"].sum()
    default = float(historical.median()) if not historical.empty else 0.0

    baseline = []
    for item in weather:
        temp = item.get("temperature_c")
        weather_factor = 1.0
        if temp is not None:
            weather_factor += max(0.0, 15.0 - float(temp)) * 0.025
            weather_factor -= max(0.0, float(temp) - 18.0) * 0.015
        if item.get("snow_or_frost"):
            weather_factor += 0.08
        baseline.append(round(max(default * weather_factor, 0.0), 3))
    return baseline


def _local_weather_series(frame: pd.DataFrame) -> list[dict]:
    if frame.empty:
        return []

    data = frame.copy()
    data["date"] = pd.to_datetime(data["date"]).dt.strftime("%Y-%m-%d")
    grouped = data.groupby("date", as_index=False).agg(
        temperature_c=("mean_outside_temperature_c", "mean"),
    )
    result = []
    for row in grouped.to_dict(orient="records"):
        temperature_c = None if pd.isna(row["temperature_c"]) else round(float(row["temperature_c"]), 2)
        result.append(
            {
                "x": row["date"],
                "temperature_c": temperature_c,
                "precipitation_mm": None,
                "snow_or_frost": temperature_c is not None and temperature_c <= 0,
                "wind_kmh": None,
                "cloud_cover_percent": None,
                "source": "csv",
            }
        )
    return result


def _mold_specific_energy_threshold(period_name: str) -> float:
    return {
        "day": 0.08,
        "week": 0.55,
        "month": 2.4,
        "quarter": 7.2,
        "year": 22.0,
    }.get(period_name, 2.4)


def _mold_risk_assessment(
    frame: pd.DataFrame,
    baseline_energy: list[float] | None,
    weather: list[dict] | None,
    period_name: str,
) -> dict:
    if frame.empty:
        return {
            "score": 0,
            "level": "unknown",
            "label": "Nicht verfügbar",
            "reasons": [],
            "caveat": "Keine Daten für eine Schimmelrisiko-Abschätzung vorhanden.",
        }

    actual_total = float(frame["energyusage_kwh"].sum())
    living_space = float(frame["livingspace_m2"].max()) if not frame["livingspace_m2"].isna().all() else 0.0
    specific_energy = actual_total / living_space if living_space > 0 else 0.0
    baseline_total = float(sum(baseline_energy or []))

    weather_points = weather or _local_weather_series(frame)
    temperatures = [float(item["temperature_c"]) for item in weather_points if item.get("temperature_c") is not None]
    avg_temperature = round(sum(temperatures) / len(temperatures), 2) if temperatures else None
    cold_days = sum(1 for temp in temperatures if temp <= 5)
    frost_days = sum(1 for item in weather_points if item.get("snow_or_frost") or (item.get("temperature_c") is not None and float(item["temperature_c"]) <= 0))
    wet_days = sum(1 for item in weather_points if (item.get("precipitation_mm") or 0) >= 4)

    score = 0
    reasons: list[str] = []

    baseline_ratio = actual_total / baseline_total if baseline_total > 0 else None
    if baseline_ratio is not None:
        if baseline_ratio < 0.7:
            score += 40
            reasons.append("Der aktuelle Heizverbrauch liegt deutlich unter dem witterungsbereinigten Erwartungswert.")
        elif baseline_ratio < 0.85:
            score += 24
            reasons.append("Der aktuelle Heizverbrauch liegt spürbar unter dem witterungsbereinigten Erwartungswert.")

    if avg_temperature is not None and avg_temperature <= 8:
        if cold_days >= max(1, len(temperatures) // 3):
            score += 12
            reasons.append("Über den betrachteten Zeitraum traten mehrere kalte Außentemperaturen auf.")
        if frost_days >= max(1, len(temperatures) // 5):
            score += 16
            reasons.append("Frostige Tage erhöhen das Risiko für kalte Bauteiloberflächen.")

    if avg_temperature is not None and avg_temperature <= 8 and specific_energy < _mold_specific_energy_threshold(period_name):
        score += 18
        reasons.append("Die spezifische Heizenergie pro Quadratmeter ist für die kalte Wetterlage eher niedrig.")

    if avg_temperature is not None and avg_temperature <= 10 and wet_days >= 2:
        score += 8
        reasons.append("Feuchte Wetterphasen können zusammen mit geringer Beheizung problematisch sein.")

    score = min(score, 100)

    if score >= 60:
        level = "elevated"
        label = "Erhöht"
    elif score >= 30:
        level = "medium"
        label = "Mittel"
    else:
        level = "low"
        label = "Niedrig"

    return {
        "score": int(score),
        "level": level,
        "label": label,
        "reasons": reasons,
        "avg_temperature_c": avg_temperature,
        "cold_days": cold_days,
        "frost_days": frost_days,
        "specific_energy_kwh_per_m2": round(specific_energy, 3),
        "caveat": "Deterministische Demo-Risikoabschätzung ohne Innenraumfeuchte, Oberflächentemperaturen oder Lüftungssensorik.",
    }


def _mold_warning(mold_risk: dict) -> str | None:
    if mold_risk.get("level") == "elevated":
        return "Erhöhtes Schimmelrisiko: geringer Heizverbrauch trotz kalter Wetterlage. Bitte Raumtemperatur und Lüftungsverhalten prüfen."
    if mold_risk.get("level") == "medium":
        return "Mittlere Schimmelrisiko-Indikation: Heizniveau und kalte Wetterphasen sollten beobachtet werden."
    return None


def chart_payload(
    connection,
    scope_type: str,
    scope_id: str | None,
    period: str,
    offset: int,
    include_weather: bool,
    analysis_provider: str | None,
) -> dict:
    cache_key = _chart_cache_key(scope_type, scope_id, period, offset, include_weather, analysis_provider)
    with _CACHE_LOCK:
        cached = _CHART_CACHE.get(cache_key)
    if cached is not None:
        return deepcopy(cached)

    # Main chart pipeline:
    # 1. build deterministic scope context and actual series locally
    # 2. ask AI provider only for forecast, optimization and explanation
    base_context = chart_context_base(
        connection,
        scope_type,
        scope_id,
        period,
        offset,
        include_weather,
    )
    ai_context = {
        "scope": base_context["scope"],
        "period": base_context["period"],
        "requested_datasets": {
            "actual_series": base_context["series"],
            "summary": base_context["summary"],
            "weather": base_context["weather"],
            "calendar": base_context["calendar"],
        },
        "x_axis": base_context["x_axis"],
        "series": base_context["series"],
        "baseline_energy": base_context["baseline_energy"],
        "average_emission_factor_kg_per_kwh": base_context["average_emission_factor_kg_per_kwh"],
        "weather": base_context["weather"],
        "weather_location": base_context["weather_location"],
        "calendar": base_context["calendar"],
        "summary": base_context["summary"],
    }
    ai_result = ai_analysis_service.analyze_chart(ai_context, analysis_provider)
    ai_dict = ai_analysis_service.dump_model(ai_result)
    points = ai_dict["points"]

    payload = {
        "scope": base_context["scope"],
        "period": base_context["period"],
        "x_axis": base_context["x_axis"],
        "series": {
            "actual_energy": base_context["series"]["actual_energy"],
            "predicted_energy": [point["predicted_energy"] for point in points],
            "optimized_energy": [point["optimized_energy"] for point in points],
            "actual_co2": base_context["series"]["actual_co2"],
            "predicted_co2": [point["predicted_co2"] for point in points],
            "optimized_co2": [point["optimized_co2"] for point in points],
        },
        "summary": base_context["summary"],
        "warnings": base_context.get("warnings", []),
        "mold_risk": base_context["mold_risk"],
        "weather_location": base_context["weather_location"],
        "anomalies": ai_dict["anomalies"],
        "ai_explanations": {
            "provider": ai_dict["provider"],
            "fallback_used": ai_dict["fallback_used"],
            "explanations": ai_dict["explanations"],
            "influencing_factors": ai_dict["influencing_factors"],
        },
        "context": {"weather": base_context["weather"], "calendar": base_context["calendar"]},
        "data_source_info": {
            **base_context["data_source_info"],
            "predicted_and_optimized_values": f"Chart provider '{ai_dict['provider']}' with validation and local fallback",
        },
    }
    with _CACHE_LOCK:
        _CHART_CACHE[cache_key] = deepcopy(payload)
    return payload


def chart_context_base(
    connection,
    scope_type: str,
    scope_id: str | None,
    period: str,
    offset: int,
    include_weather: bool,
) -> dict:
    # Deterministic chart context shared by chart/report/chat. This function
    # intentionally does not call any AI provider.
    period_info = resolve_period(period, offset)
    labels = period_buckets(period_info["start"], period_info["end"], period_info["granularity"])
    full_frame = _read_frame(connection, scope_type, scope_id)
    period_frame = _frame_for_period(full_frame, period_info["start"], period_info["end"])
    actual_energy, actual_co2 = _aggregate_series(period_frame, labels, period_info["granularity"])
    weather_warnings: list[str] = []
    weather_status: dict = {}
    weather_location = None
    if include_weather:
        weather_bundle = weather_context(period_frame if not period_frame.empty else full_frame, labels, period_info["granularity"], True)
        weather = weather_bundle["series"]
        weather_warnings = weather_bundle["warnings"]
        weather_location = weather_bundle.get("location")
        weather_status = weather_bundle["status"]
    else:
        weather = [
            {
                "x": label,
                "temperature_c": None,
                "precipitation_mm": None,
                "snow_or_frost": False,
                "wind_kmh": None,
                "cloud_cover_percent": None,
                "source": "disabled",
            }
            for label in labels
        ]
        weather_status = {"tomorrow": {"ok": True, "indicator": "disabled", "description": "Weather toggle disabled.", "source": "disabled"}}
    zipcode = None if full_frame.empty else str(full_frame.iloc[0]["zipcode"])
    holidays = holiday_context(labels, zipcode)
    baseline = _baseline_energy(full_frame, labels, period_info["granularity"], weather)
    emission_factor_kg = (
        float(full_frame["emission_factor_g_per_kwh"].mean()) / 1000 if not full_frame.empty else 0.2
    )
    mold_risk = _mold_risk_assessment(period_frame if not period_frame.empty else full_frame, baseline, weather, period)
    mold_warning = _mold_warning(mold_risk)
    warnings = list(weather_warnings)
    if mold_warning:
        warnings.append(mold_warning)
    return {
        "scope": _scope_info(full_frame, scope_type, scope_id),
        "period": {
            "name": period,
            "offset": offset,
            "start": period_info["start"].isoformat(),
            "end": period_info["end"].isoformat(),
            "granularity": period_info["granularity"],
        },
        "x_axis": labels,
        "series": {"actual_energy": actual_energy, "actual_co2": actual_co2},
        "baseline_energy": baseline,
        "average_emission_factor_kg_per_kwh": emission_factor_kg,
        "weather": weather,
        "weather_location": weather_location,
        "warnings": warnings,
        "mold_risk": mold_risk,
        "weather_status": weather_status,
        "calendar": holidays,
        "summary": _summary(period_frame),
        "data_source_info": {
            "actual_values": "SQLite records imported from CSV",
            "co2_calculation": "energyusage_kwh * emission_factor_g_per_kwh / 1000",
            "mold_risk": "Deterministic demo heuristic based on heating level, outside temperature and weather context. No humidity or surface sensors included.",
            "weather_location": weather_location.get("query_used") if weather_location else "No weather location available",
            "weather": "Open-Meteo range data for historical and near-future periods, optional Tomorrow.io realtime supplement for today, otherwise CSV temperature plus local weather fallback",
            "tomorrow_status": weather_status.get("tomorrow", {}).get("description", "Unknown"),
            "calendar": "German holiday and weekend indicators from local holiday service by ZIP/state fallback.",
        },
    }


def _ranked_scope_summary(frame: pd.DataFrame, group_columns: list[str], label_builder, limit: int = 10) -> list[dict]:
    if frame.empty:
        return []

    grouped = frame.groupby(group_columns, as_index=False).agg(
        energyusage_kwh=("energyusage_kwh", "sum"),
        co2_g=("co2_g", "sum"),
        apartment_count=("apartment_id", "nunique"),
        record_count=("id", "count"),
    )
    grouped = grouped.sort_values("co2_g", ascending=False).head(limit)
    result = []
    for row in grouped.to_dict(orient="records"):
        result.append(
            {
                "id": row[group_columns[0]],
                "label": label_builder(row),
                "total_energy_kwh": round(float(row["energyusage_kwh"]), 3),
                "total_co2_kg": round(float(row["co2_g"]) / 1000, 3),
                "apartment_count": int(row["apartment_count"]),
                "record_count": int(row["record_count"]),
            }
        )
    return result


def broad_context(connection) -> dict:
    frame = _read_frame(connection)
    # The chat provider receives compact deterministic rankings instead of raw
    # CSV rows. This is enough for portfolio questions without uploading all
    # source data to Gemini.
    return {
        "scope": _scope_info(frame, "total", None),
        "summary": _summary(frame),
        "city_rankings": _ranked_scope_summary(
            frame,
            ["city_id", "city"],
            lambda row: row["city"],
        ),
        "building_rankings": _ranked_scope_summary(
            frame,
            ["building_id", "street", "housenumber", "city"],
            lambda row: f"{row['street']} {row['housenumber']}, {row['city']}",
        ),
        "apartment_rankings": _ranked_scope_summary(
            frame,
            ["apartment_id", "apartment_number", "street", "housenumber", "city"],
            lambda row: f"Wohnung {row['apartment_number']}, {row['street']} {row['housenumber']}, {row['city']}",
        ),
    }



